version: '3'
networks:
  avaliacao_network:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/users_db
      DATABASE_USERNAME: pp_user
      DATABASE_PASSWORD: pp_user
    depends_on:
      - db      
    networks:
      avaliacao_network:
    ports:
      - "8080:8080"      
  db:
    image: mariadb:10.3
    networks:
      avaliacao_network:    
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_USER: pp_user
      MYSQL_PASSWORD: pp_user
      MYSQL_ROOT_PASSWORD: root_password
